name: Vibrant Media Prouctions
favicon: null
layout_spectrum: 0.4222390172071755
typography_spectrum: 0.40585409267805517
title: 'Orlando Video Production | Videographer Orlando'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.27455248055048287
  lightness: 0.9907430454622954
  saturation: 0.8304600773844868
  rhythmicContrast: 0.26441304734908044
purpose: []
